### ISSUE TITLE
While building the code first time it throws the following error

### ISSUE THREAD

**Issue by riginoommen** [IBM/template-graphql-typescript#8]
```bash
riginoommen-mac:template-graphql-typescript riginoommen$ npm run build

> template-graphql-typescript@1.0.0 prebuild /Users/riginoommen/study/template-graphql-typescript
> npm run clean


> template-graphql-typescript@1.0.0 clean /Users/riginoommen/study/template-graphql-typescript
> rimraf dist


> template-graphql-typescript@1.0.0 build /Users/riginoommen/study/template-graphql-typescript
> tsc

test/pact-publish.ts:3:31 - error TS2307: Cannot find module '@pact-foundation/pact'.

3 import {VerifierOptions} from '@pact-foundation/pact';
                                ~~~~~~~~~~~~~~~~~~~~~~~

test/pact-verify.ts:3:41 - error TS2307: Cannot find module '@pact-foundation/pact'.

3 import {Verifier, VerifierOptions} from '@pact-foundation/pact';
                                          ~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.
```

**Comment by riginoommen** [comment]
> ```shell
> riginoommen-mac:template-graphql-typescript riginoommen$ npm run build
> 
> > template-graphql-typescript@1.0.0 prebuild /Users/riginoommen/study/template-graphql-typescript
> > npm run clean
> 
> 
> > template-graphql-typescript@1.0.0 clean /Users/riginoommen/study/template-graphql-typescript
> > rimraf dist
> 
> 
> > template-graphql-typescript@1.0.0 build /Users/riginoommen/study/template-graphql-typescript
> > tsc
> 
> test/pact-publish.ts:3:31 - error TS2307: Cannot find module '@pact-foundation/pact'.
> 
> 3 import {VerifierOptions} from '@pact-foundation/pact';
>                                 ~~~~~~~~~~~~~~~~~~~~~~~
> 
> test/pact-verify.ts:3:41 - error TS2307: Cannot find module '@pact-foundation/pact'.
> 
> 3 import {Verifier, VerifierOptions} from '@pact-foundation/pact';
>                                           ~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Found 2 errors.
> ```

When i try to install the `@pact-foundation/pact` it shows error after the postinstall

**Comment by csantanapr** [comment]
not reproducible
